# Generated by Django 5.2.8 on 2025-11-06 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('massage', models.TextField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$', message='phone is not valid'), django.core.validators.MaxLengthValidator(20)])),
                ('sub_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shelter.owner')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(max_length=60)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('adopted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shelter.owner')),
                ('siblings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shelter.pet')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['name'],
            },
        ),
    ]
